name             'soroco_apt'
maintainer       'SOROCO'
maintainer_email 'warren.castro@possible.com'
license          'All rights reserved'
description      'Installs/Configures soroco_apt_update'
long_description 'Installs/Configures soroco_apt_update'
version          '0.1.0'
depends 'apt', '~> 2.8.2'
